### ISSUE TITLE
Upgraded to IntelliJ 2019.3 and Ebean enhancer fails for ebean 11

### ISSUE THREAD

**Issue by risenhoover** [ebean-orm-tools/ebean-idea-enhancer#5]
I'm using io.ebean:ebean:11.2

After upgrading my IDEA to 2019.3, I'm getting this error now - 
```Exception in thread "main" java.lang.NoSuchMethodError: io.ebean.bean.EntityBeanIntercept.preSetter(ZILjava/lang/Object;Ljava/lang/Object;)V
	at co.quantsoft.model.WatchlistRow._ebean_set_country(WatchlistRow.java:1)
```

which, according to this page https://github.com/ebean-orm/ebean/issues/1440 - indicates the version of ebean-agent is wrong. I checked in the ebean-idea directory and the files listed there are ebean-agent-12.1.8.jar, which seems like a suspicious mismatch.

**Comment by rbygrave** [comment]
The above doesn't tell us the error but just the line of code?  Can you include the actual error?

> ebean-agent-12.1.8.jar, which seems like a suspicious mismatch.

The 12.x agent should be fine to use with all versions of Ebean 11.x.

**Comment by risenhoover** [comment]
Yes you are right. My apologies. Here's a better stack trace:

```
Exception in thread "main" java.lang.NoSuchMethodError: io.ebean.bean.EntityBeanIntercept.preSetter(ZILjava/lang/Object;Ljava/lang/Object;)V
	at co.x.model.Bar._ebean_set_rsi(Bar.java:1)
	at co.x.model.Bar.<init>(Bar.java:43)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
```

Same basic error, different location.

**Comment by rbygrave** [comment]
> NoSuchMethodError: io.ebean.bean.EntityBeanIntercept.preSetter(ZILjava/lang/Object;Ljava/lang/Object;)V

So in Ebean 11.4.1 there was the change - https://github.com/ebean-orm/ebean/issues/1198  ... and that makes the newer agent incompatible with 11.2.x.

I believe the options are:
1. Update Ebean to some version equal or higher than 11.4.1
2. Downgrade the agent used by the Ebean IntelliJ plugin.  This can be done by putting a ebean-agent-...jar file into a ~/.ebean directory and turning the agent off and then on.

**Comment by risenhoover** [comment]
I upgraded the ebean to 12.1.8 (for some reason, IntelliJ doesn't show this version in Maven so I had to download it directly). After fixing up a bunch of other dependencies, I'm getting a new error:

```
Exception in thread "main" java.lang.NoSuchFieldError: _objectFieldValueSeparatorWithSpaces
	at io.ebeaninternal.server.text.json.DJsonContext$Pretty.<init>(DJsonContext.java:62)
	at io.ebeaninternal.server.text.json.DJsonContext.<clinit>(DJsonContext.java:48)
	at io.ebeaninternal.server.core.InternalConfiguration.createJsonContext(InternalConfiguration.java:339)
	at io.ebeaninternal.server.core.DefaultServer.<init>(DefaultServer.java:287)
	at io.ebeaninternal.server.core.DefaultContainer.createServer(DefaultContainer.java:122)
	at io.ebeaninternal.server.core.DefaultContainer.createServer(DefaultContainer.java:36)
	at io.ebean.EbeanServerFactory.createInternal(EbeanServerFactory.java:109)
	at io.ebean.EbeanServerFactory.create(EbeanServerFactory.java:70)
	at co.x.xx.main(X.java:71)
```

**Comment by rbygrave** [comment]
Ah, this version of Ebean requires jackson-core 2.9+ ... for "pretty json
printing".

This error suggests to me that the classpath has an older version of
jackson-core (less than version 2.9).

**Comment by risenhoover** [comment]
Thanks for the tip - I didn't have any jackson-core in the classpath but I added com.fasterxml.jackson.core:jackson-core:2.9.9 and I get the same error.  I can see in the source where this field is referenced and I can unpack the jar to confirm the field exists.

**Comment by rbygrave** [comment]
Have you done a maven dependency tree ?

mvn dependency:tree

*>  I didn't have any jackson-core in the classpath*

The app would have had a dependency on jackson-core because it is a
transitive dependency of Ebean - Ebean would have brought it into the
classpath.  Using mvn dependency:tree shows you the dependencies that are
brought into the classpath (and test classpath).

**Comment by risenhoover** [comment]
I had a problem with IntelliJ that was not showing me io.ebean:ebean:xx versions larger than 11.2 from Maven (which is how I ended up at the top of the ticket). To resolve it I downloaded 12.1.8 manually and added the transitive jars, but still it didn't work.

I was able to get IntelliJ to find *all* the ebean versions, then I selected v. 11.45.1 (avoiding v. 12), and it works now. IntelliJ finds all the transitive jars as you know. Thanks for all your help.
